---
abstract: 'Provides a ping action for consuming controllers'
author:
  - 'Nicholas Perez <nperez@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100660'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-TraitFor-Controller-Ping
requires:
  Catalyst::Runtime: 5.80021
resources:
  repository: git://github.com/nperez/catalyst-traitfor-controller-ping.git
version: 0.001
